### ISSUE TITLE
Timeout en DescargaSAT.search()

### ISSUE THREAD

**Issue by ppaez** [LinuxCabal/admin-cfdi#62]
Documentando el error que comentamos durante la reunión.  Sucede en pocas ocasiones, lo estamos analizando para prevenirlo, es un timeout porque la expected condition no se da.  Este es el mensaje: 

```
(env34) pp@g6:~/admin-cfdi$ py -m unittest functional_DescargaSAT.DescargaSAT.test_emitidas
E
======================================================================
ERROR: test_emitidas (functional_DescargaSAT.DescargaSAT)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pp/admin-cfdi/functional_DescargaSAT.py", line 162, in test_emitidas
    facturas_emitidas=True)
  File "/home/pp/admin-cfdi/admincfdi/pyutil.py", line 1891, in search
    wait.until(EC.staleness_of(results_table))
  File "/home/pp/admin-cfdi/env34/lib/python3.4/site-packages/selenium-2.45.0-py3.4.egg/selenium/webdriver/support/wait.py", line 75, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

----------------------------------------------------------------------
Ran 1 test in 29.429s
```

**Comment by ppaez** [comment]
Antes de usar los explicit waits, había un sleep(3) para facturas emitidas y un sleep(15) para facturas recibidas sin especificar día, después de enviar la forma de búsqueda.  Con los explicit waits se estableció el timeout en 10 segundos; he estado probando con 15 segundos y con mis condiciones de conexión no se ha observado este error.

**Comment by ppaez** [comment]
Se está corrigiendo en #63
